kind = "web"
previewPath = "/"
title = "Is Everyone Here"
version = "1.0.0"
id = "artifacts/is-everyone-here"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 25655
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/is-everyone-here run dev"

[services.env]
PORT = "25655"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/is-everyone-here", "run", "build"]
publicDir = "artifacts/is-everyone-here/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
